name: xanoo_admin
description: "A new Flutter project."

publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.3.2
  fpdart: ^1.1.0
  supabase_flutter: ^2.5.6
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  get_it: ^7.7.0
  dotted_border: ^2.1.0
  file_picker: ^5.2.0
  uuid: ^4.4.0
  internet_connection_checker_plus: ^2.5.0
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  supabase: ^2.2.4
  icons_launcher: ^3.0.0
  equatable: ^2.0.5

icons_launcher:
  image_path: "assets/icons/app_logo.png"
  platforms:
    linux:
      enable: true
      image_path: "assets/icons/app_logo.png"
      icon_size: 128
      output_path: "linux/snap/gui"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
